import style from '../sass/style.scss'

import './front/event-map'
import './front/mode-chooser'
import './front/navigation'
import './front/jquery.fluidbox'
import './front/night-mode'
import './front/skip-link-focus-fix'
import './front/video-player'
import './front/project-fluidBox'